export const seedAccounts = [
  {
    id: 1,
    userId: 1,
    name: 'NIC Asia',
    type: 'bank',
    institution: 'NIC Asia Bank',
    balance: 40000,
    currency: 'NPR',
    lastFour: '4821',
  },
  {
    id: 2,
    userId: 1,
    name: 'Nabil Savings',
    type: 'bank',
    institution: 'Nabil Bank',
    balance: 15000,
    currency: 'NPR',
    lastFour: '1190',
  },
  {
    id: 3,
    userId: 1,
    name: 'eSewa',
    type: 'wallet',
    provider: 'eSewa',
    balance: 8500,
    currency: 'NPR',
  },
  {
    id: 4,
    userId: 1,
    name: 'Khalti',
    type: 'wallet',
    provider: 'Khalti',
    balance: 5000,
    currency: 'NPR',
  },
  {
    id: 5,
    userId: 1,
    name: 'Fonepay',
    type: 'wallet',
    provider: 'Fonepay',
    balance: 5950,
    currency: 'NPR',
  },
  {
    id: 6,
    userId: 1,
    name: 'Cash',
    type: 'cash',
    provider: 'Cash',
    balance: 12000,
    currency: 'NPR',
  },
]

export const seedTransactions = [
  {
    id: 1,
    userId: 1,
    accountId: 1,
    categoryId: 1,
    title: 'Monthly Salary',
    amount: 65000,
    type: 'income',
    category: 'Salary',
    paymentSource: 'Bank',
    date: '2026-08-01',
    description: 'August salary credited to NIC Asia',
  },
  {
    id: 2,
    userId: 1,
    accountId: 6,
    categoryId: 3,
    title: 'Weekday lunches',
    amount: 4200,
    type: 'expense',
    category: 'Food',
    paymentSource: 'Cash',
    date: '2026-08-04',
    description: 'Meals around Itahari',
  },
  {
    id: 3,
    userId: 1,
    accountId: 3,
    categoryId: 4,
    title: 'Local bus and ride',
    amount: 1850,
    type: 'expense',
    category: 'Transport',
    paymentSource: 'eSewa',
    date: '2026-08-06',
    description: 'Commute and weekend travel',
  },
  {
    id: 4,
    userId: 1,
    accountId: 1,
    categoryId: 5,
    title: 'Room rent',
    amount: 12000,
    type: 'expense',
    category: 'Rent',
    paymentSource: 'Bank',
    date: '2026-08-02',
    description: 'August rent transfer',
  },
  {
    id: 5,
    userId: 1,
    accountId: 4,
    categoryId: 6,
    title: 'WorldLink internet',
    amount: 1500,
    type: 'expense',
    category: 'Internet',
    paymentSource: 'Khalti',
    date: '2026-08-05',
    description: 'Monthly fibre plan',
  },
  {
    id: 6,
    userId: 1,
    accountId: 5,
    categoryId: 7,
    title: 'Bhatbhateni groceries',
    amount: 3300,
    type: 'expense',
    category: 'Shopping',
    paymentSource: 'Fonepay',
    date: '2026-08-09',
    description: 'Household supplies',
  },
  {
    id: 7,
    userId: 1,
    accountId: 3,
    categoryId: 8,
    title: 'Movie night',
    amount: 900,
    type: 'expense',
    category: 'Entertainment',
    paymentSource: 'eSewa',
    date: '2026-08-10',
    description: 'QFX tickets',
  },
  {
    id: 8,
    userId: 1,
    accountId: 2,
    categoryId: 9,
    title: 'Online course',
    amount: 2500,
    type: 'expense',
    category: 'Education',
    paymentSource: 'Bank',
    date: '2026-08-12',
    description: 'Frontend workshop fee',
  },
  {
    id: 9,
    userId: 1,
    accountId: 4,
    categoryId: 3,
    title: 'Coffee and snacks',
    amount: 1450,
    type: 'expense',
    category: 'Food',
    paymentSource: 'Khalti',
    date: '2026-08-14',
    description: 'Cafe visits this week',
  },
  {
    id: 10,
    userId: 1,
    accountId: 1,
    categoryId: 10,
    title: 'Electricity bill',
    amount: 2100,
    type: 'expense',
    category: 'Utilities',
    paymentSource: 'Bank',
    date: '2026-08-08',
    description: 'NEA payment',
  },
  {
    id: 11,
    userId: 1,
    accountId: 6,
    categoryId: 3,
    title: 'Weekend dinner',
    amount: 1850,
    type: 'expense',
    category: 'Food',
    paymentSource: 'Cash',
    date: '2026-08-16',
    description: 'Family dinner',
  },
  {
    id: 12,
    userId: 1,
    accountId: 3,
    categoryId: 2,
    title: 'Freelance UI work',
    amount: 12000,
    type: 'income',
    category: 'Freelance',
    paymentSource: 'eSewa',
    date: '2026-08-11',
    description: 'Client milestone payment',
  },
  {
    id: 13,
    userId: 1,
    accountId: 5,
    categoryId: 4,
    title: 'Fuel',
    amount: 2200,
    type: 'expense',
    category: 'Transport',
    paymentSource: 'Fonepay',
    date: '2026-08-18',
    description: 'Scooter petrol',
  },
  {
    id: 14,
    userId: 1,
    accountId: 4,
    categoryId: 11,
    title: 'Pharmacy',
    amount: 650,
    type: 'expense',
    category: 'Health',
    paymentSource: 'Khalti',
    date: '2026-08-17',
    description: 'OTC medicines',
  },
  {
    id: 15,
    userId: 1,
    accountId: 6,
    categoryId: 7,
    title: 'Clothes',
    amount: 2800,
    type: 'expense',
    category: 'Shopping',
    paymentSource: 'Cash',
    date: '2026-07-28',
    description: 'Seasonal wear',
  },
  {
    id: 16,
    userId: 1,
    accountId: 1,
    categoryId: 1,
    title: 'Monthly Salary',
    amount: 65000,
    type: 'income',
    category: 'Salary',
    paymentSource: 'Bank',
    date: '2026-07-01',
    description: 'July salary',
  },
  {
    id: 17,
    userId: 1,
    accountId: 1,
    categoryId: 5,
    title: 'Room rent',
    amount: 12000,
    type: 'expense',
    category: 'Rent',
    paymentSource: 'Bank',
    date: '2026-07-02',
    description: 'July rent',
  },
  {
    id: 18,
    userId: 1,
    accountId: 6,
    categoryId: 3,
    title: 'Groceries and dining',
    amount: 6350,
    type: 'expense',
    category: 'Food',
    paymentSource: 'Cash',
    date: '2026-07-15',
    description: 'July food spend',
  },
  {
    id: 19,
    userId: 1,
    accountId: 2,
    categoryId: 12,
    title: 'Emergency fund transfer',
    amount: 8000,
    type: 'expense',
    category: 'Transfer',
    paymentSource: 'Bank',
    date: '2026-08-03',
    description: 'Moved to savings goal',
  },
  {
    id: 20,
    userId: 1,
    accountId: 3,
    categoryId: 8,
    title: 'Streaming',
    amount: 499,
    type: 'expense',
    category: 'Entertainment',
    paymentSource: 'eSewa',
    date: '2026-08-07',
    description: 'YouTube Premium',
  },
]

export const seedBudgets = [
  {
    id: 1,
    userId: 1,
    categoryId: 3,
    category: 'Food',
    period: '2026-08',
    amount: 10000,
    spent: 7500,
  },
  {
    id: 2,
    userId: 1,
    categoryId: 4,
    category: 'Transport',
    period: '2026-08',
    amount: 5000,
    spent: 4050,
  },
  {
    id: 3,
    userId: 1,
    categoryId: 5,
    category: 'Rent',
    period: '2026-08',
    amount: 12000,
    spent: 12000,
  },
  {
    id: 4,
    userId: 1,
    categoryId: 7,
    category: 'Shopping',
    period: '2026-08',
    amount: 6000,
    spent: 3300,
  },
  {
    id: 5,
    userId: 1,
    categoryId: 8,
    category: 'Entertainment',
    period: '2026-08',
    amount: 2500,
    spent: 1399,
  },
  {
    id: 6,
    userId: 1,
    categoryId: 6,
    category: 'Internet',
    period: '2026-08',
    amount: 2000,
    spent: 1500,
  },
]

export const seedSavingsGoals = [
  {
    id: 1,
    userId: 1,
    name: 'Emergency Fund',
    targetAmount: 100000,
    currentAmount: 42000,
    targetDate: '2026-12-31',
    category: 'Safety',
  },
  {
    id: 2,
    userId: 1,
    name: 'Laptop',
    targetAmount: 150000,
    currentAmount: 48000,
    targetDate: '2026-12-15',
    category: 'Work',
  },
  {
    id: 3,
    userId: 1,
    name: 'Travel',
    targetAmount: 80000,
    currentAmount: 18500,
    targetDate: '2027-04-01',
    category: 'Lifestyle',
  },
  {
    id: 4,
    userId: 1,
    name: 'Education',
    targetAmount: 60000,
    currentAmount: 22000,
    targetDate: '2026-11-01',
    category: 'Growth',
  },
  {
    id: 5,
    userId: 1,
    name: 'New Phone',
    targetAmount: 45000,
    currentAmount: 9000,
    targetDate: '2026-10-20',
    category: 'Lifestyle',
  },
]

export const seedNotifications = [
  {
    id: 1,
    userId: 1,
    title: 'Food budget at 75%',
    body: 'You have NPR 2,500 left in your Food budget this month.',
    type: 'warning',
    read: false,
    createdAt: '2026-08-18T09:12:00',
  },
  {
    id: 2,
    userId: 1,
    title: 'Salary recorded',
    body: 'August salary of NPR 65,000 was added to NIC Asia.',
    type: 'success',
    read: false,
    createdAt: '2026-08-01T10:04:00',
  },
  {
    id: 3,
    userId: 1,
    title: 'Laptop goal update',
    body: 'At your current pace you can reach your laptop goal in about 4 months.',
    type: 'info',
    read: true,
    createdAt: '2026-08-15T18:40:00',
  },
]

export const seedInsights = [
  {
    id: 1,
    tone: 'warning',
    title: 'Food spending is up',
    message: 'You spent 18% more on food this month compared with July.',
  },
  {
    id: 2,
    tone: 'success',
    title: 'Savings are moving',
    message: 'Your savings increased by 12% compared with last month.',
  },
  {
    id: 3,
    tone: 'info',
    title: 'Laptop goal is on track',
    message: 'You are on track to reach your laptop goal in 4 months.',
  },
  {
    id: 4,
    tone: 'danger',
    title: 'Rent used the full budget',
    message: 'Your rent budget is fully used for August. Other housing costs will come from leftover funds.',
  },
]

export const dummyTestimonials = [
  {
    id: 1,
    name: 'Sample user — Kathmandu',
    role: 'Software engineer',
    quote:
      'I used to guess what was in eSewa versus my bank. This layout makes that split obvious without feeling noisy.',
  },
  {
    id: 2,
    name: 'Sample user — Pokhara',
    role: 'Cafe owner',
    quote:
      'Cash, Khalti, and the shop account finally live in one picture. The dummy stories here are for product preview only.',
  },
  {
    id: 3,
    name: 'Sample user — Itahari',
    role: 'Student',
    quote:
      'The savings cards helped me see whether a laptop fund was realistic. These quotes are illustrative, not real reviews.',
  },
]
