import { useEffect, useMemo, useState } from 'react'
import { LanguageContext } from './language-context'
import { STORAGE_KEYS } from '../utils/constants'

const nepaliTranslations = {
  Home: 'गृहपृष्ठ',
  Features: 'विशेषताहरू',
  'How It Works': 'कसरी काम गर्छ',
  Pricing: 'मूल्य',
  Contact: 'सम्पर्क',
  About: 'हाम्रो बारेमा',
  Dashboard: 'ड्यासबोर्ड',
  Login: 'लगइन',
  'Get Started': 'सुरु गर्नुहोस्',
  'Personal finance tools for everyday decisions.': 'दैनिक निर्णयका लागि व्यक्तिगत वित्तीय उपकरणहरू।',
  'Personal finance for Nepal': 'नेपालका लागि व्यक्तिगत वित्त व्यवस्थापन',
  'Know Where Your Money Is.': 'तपाईंको पैसा कहाँ छ थाहा पाउनुहोस्।',
  "Know Where It’s Going.": 'यो कहाँ जाँदैछ थाहा पाउनुहोस्।',
  "Know Where It's Going.": 'यो कहाँ जाँदैछ थाहा पाउनुहोस्।',
  'Finora brings bank accounts, cash, eSewa, Khalti, and Fonepay into one calm picture so you can track spending, set budgets, and see whether your goals are realistic.': 'Finora ले बैंक खाता, नगद, eSewa, Khalti र Fonepay लाई एउटै स्पष्ट दृश्यमा ल्याउँछ, जसबाट तपाईं खर्च ट्र्याक गर्न, बजेट बनाउन र आफ्ना लक्ष्य सम्भव छन् कि छैनन् हेर्न सक्नुहुन्छ।',
  'Sign in': 'साइन इन',
  'Built around NPR.': 'नेपाली रुपैयाँलाई आधार मानेर बनाइएको।',
  'What Finora helps you do': 'Finora ले तपाईंलाई के गर्न मद्दत गर्छ',
  'The product is built around a clear picture of money, not a crowded ledger.': 'यो सेवा जटिल हिसाबकिताब होइन, पैसाको स्पष्ट चित्र दिन बनाइएको हो।',
  'Expense Tracking': 'खर्च ट्र्याकिङ',
  'Record income and expenses with category, date, and payment source.': 'आम्दानी र खर्चलाई वर्ग, मिति र भुक्तानी स्रोतसहित रेकर्ड गर्नुहोस्।',
  'Budget Management': 'बजेट व्यवस्थापन',
  'See spent versus remaining for Food, Rent, Transport, and more.': 'खाना, भाडा, यातायात र अन्य शीर्षकमा खर्च भएको र बाँकी रकम हेर्नुहोस्।',
  'Financial Analytics': 'वित्तीय विश्लेषण',
  'Charts for income vs expense, category mix, and savings trend.': 'आम्दानी र खर्च, खर्चका वर्ग तथा बचतको प्रवृत्तिका चार्टहरू।',
  'Savings Goals': 'बचत लक्ष्यहरू',
  'Track Emergency Fund, laptop, travel, education, and other targets.': 'आपत्कालीन कोष, ल्यापटप, यात्रा, शिक्षा र अन्य लक्ष्यहरू ट्र्याक गर्नुहोस्।',
  'Multiple Money Sources': 'धेरै रकम स्रोतहरू',
  'Bank, cash, eSewa, Khalti, and Fonepay in one overview.': 'बैंक, नगद, eSewa, Khalti र Fonepay एउटै दृश्यमा।',
  'Financial Insights': 'वित्तीय जानकारी',
  'Plain-language notes such as food spend rising or a goal staying on track.': 'खानाको खर्च बढेको वा लक्ष्य योजनाअनुसार अघि बढेको जस्ता सरल जानकारी।',
  'How it works': 'कसरी काम गर्छ',
  'Add your money sources': 'आफ्ना रकमका स्रोत थप्नुहोस्',
  'Track transactions': 'कारोबार ट्र्याक गर्नुहोस्',
  'Set budgets': 'बजेट तय गर्नुहोस्',
  'Create savings goals': 'बचत लक्ष्य बनाउनुहोस्',
  'Understand your financial progress': 'आफ्नो वित्तीय प्रगति बुझ्नुहोस्',
  'Built for the way you manage money in Nepal.': 'नेपालमा तपाईंले पैसा व्यवस्थापन गर्ने तरिकाअनुसार बनाइएको।',
  'Balances are shown in NPR by default. Sources match everyday use: cash in hand, a bank account, and wallets you already pay with.': 'खाताको मौज्दात पूर्वनिर्धारित रूपमा नेपाली रुपैयाँमा देखाइन्छ। नगद, बैंक खाता र तपाईंले प्रयोग गर्ने डिजिटल वालेटहरू समेटिएका छन्।',
  'Start understanding your money today.': 'आजै आफ्नो पैसा बुझ्न सुरु गर्नुहोस्।',
  'Create an account to organize your money, track spending, and build a plan around your goals.': 'पैसा व्यवस्थित गर्न, खर्च ट्र्याक गर्न र आफ्ना लक्ष्यअनुसार योजना बनाउन खाता खोल्नुहोस्।',
  'Open navigation': 'नेभिगेसन खोल्नुहोस्',
  'Overview': 'अवलोकन',
  'Transactions': 'कारोबार',
  'Budgets': 'बजेट',
  'Analytics': 'विश्लेषण',
  'Accounts': 'खाताहरू',
  'Savings': 'बचत',
  'Reports': 'प्रतिवेदन',
  'Notifications': 'सूचनाहरू',
  'Settings': 'सेटिङहरू',
  'Activity': 'गतिविधि',
  'Money': 'पैसा',
  'Insights': 'अन्तर्दृष्टि',
  'Know where your money is.': 'तपाईंको पैसा कहाँ छ थाहा पाउनुहोस्।',
  'Log out': 'लगआउट',
  'Here’s your financial picture': 'यहाँ तपाईंको वित्तीय अवस्था छ',
  "Here's your financial picture": 'यहाँ तपाईंको वित्तीय अवस्था छ',
  Bank: 'बैंक',
  bank: 'बैंक',
  wallet: 'वालेट',
  cash: 'नगद',
  'Digital wallet': 'डिजिटल वालेट',
  Wallets: 'डिजिटल वालेटहरू',
  Cash: 'नगद',
  Income: 'आम्दानी',
  Expenses: 'खर्च',
  Expense: 'खर्च',
  'Budget remaining': 'बजेटमा बाँकी',
  'Income vs expense': 'आम्दानी र खर्च',
  'Monthly totals from your recorded transactions.': 'तपाईंका रेकर्ड गरिएका कारोबारको मासिक जम्मा।',
  'Savings goals': 'बचत लक्ष्यहरू',
  'Recent transactions': 'हालका कारोबारहरू',
  'Financial picture': 'वित्तीय अवस्था',
  'Bank accounts, cash, and digital wallets.': 'बैंक खाता, नगद र डिजिटल वालेटहरू।',
  'Add source': 'स्रोत थप्नुहोस्',
  'Add money source': 'रकमको स्रोत थप्नुहोस्',
  'Edit money source': 'रकमको स्रोत सम्पादन गर्नुहोस्',
  Name: 'नाम',
  Type: 'प्रकार',
  Provider: 'सेवा प्रदायक',
  Balance: 'मौज्दात',
  Cancel: 'रद्द गर्नुहोस्',
  Save: 'बचत गर्नुहोस्',
  'Account updated.': 'खाता अद्यावधिक भयो।',
  'Account added.': 'खाता थपियो।',
  'Delete money source?': 'रकमको स्रोत मेटाउने?',
  'This source and its associated transactions will be permanently removed.': 'यो स्रोत र यससँग सम्बन्धित कारोबार स्थायी रूपमा हटाइनेछन्।',
  Delete: 'मेटाउनुहोस्',
  'Account deleted.': 'खाता मेटाइयो।',
  'Monthly category limits with spent and remaining amounts.': 'खर्च भएको र बाँकी रकमसहितका मासिक वर्गगत सीमा।',
  'Add budget': 'बजेट थप्नुहोस्',
  'Edit budget': 'बजेट सम्पादन गर्नुहोस्',
  'Budget amount': 'बजेट रकम',
  'Budget added.': 'बजेट थपियो।',
  'Budget updated.': 'बजेट अद्यावधिक भयो।',
  'Delete budget?': 'बजेट मेटाउने?',
  'This budget will be permanently removed.': 'यो बजेट स्थायी रूपमा हटाइनेछ।',
  'Budget deleted.': 'बजेट मेटाइयो।',
  'Charts summarize your recorded financial activity.': 'तपाईंका रेकर्ड गरिएका वित्तीय गतिविधिको सारांश चार्ट।',
  'Savings trend': 'बचतको प्रवृत्ति',
  'Category spending': 'वर्गअनुसार खर्च',
  'Payment-source spending': 'भुक्तानी स्रोतअनुसार खर्च',
  'Where expenses went this period.': 'यस अवधिमा खर्च कहाँ भयो।',
  Budget: 'बजेट',
  Spent: 'खर्च',
  Left: 'बाँकी',
  Target: 'लक्ष्य',
  of: 'मध्ये',
  'Over budget': 'बजेट नाघ्यो',
  Watch: 'ध्यान दिनुहोस्',
  'On track': 'योजनाअनुसार',
  'No transactions match': 'कुनै कारोबार भेटिएन',
  'Try clearing filters or add a new transaction.': 'फिल्टर हटाउनुहोस् वा नयाँ कारोबार थप्नुहोस्।',
  Source: 'स्रोत',
  'Salary, rent, eSewa...': 'तलब, भाडा, eSewa...',
  'Updates related to your account and financial activity.': 'तपाईंको खाता र वित्तीय गतिविधिसँग सम्बन्धित अद्यावधिकहरू।',
  'No notifications yet.': 'अहिलेसम्म कुनै सूचना छैन।',
  Read: 'पढिएको',
  New: 'नयाँ',
  'Mark read': 'पढिएको भनेर चिन्ह लगाउनुहोस्',
  'Reports use your saved transactions.': 'प्रतिवेदनहरूले तपाईंका सुरक्षित कारोबार प्रयोग गर्छन्।',
  'Export CSV': 'CSV निर्यात गर्नुहोस्',
  'Print report': 'प्रतिवेदन प्रिन्ट गर्नुहोस्',
  'Report type': 'प्रतिवेदनको प्रकार',
  Summary: 'सारांश',
  'Net movement': 'कुल परिवर्तन',
  Category: 'वर्ग',
  Date: 'मिति',
  Amount: 'रकम',
  'CSV downloaded.': 'CSV डाउनलोड भयो।',
  'Emergency fund, laptop, travel, education, and more.': 'आपत्कालीन कोष, ल्यापटप, यात्रा, शिक्षा र अन्य लक्ष्यहरू।',
  'Add goal': 'लक्ष्य थप्नुहोस्',
  'Edit goal': 'लक्ष्य सम्पादन गर्नुहोस्',
  'Goal name': 'लक्ष्यको नाम',
  'Target amount': 'लक्ष्य रकम',
  'Current amount': 'हालको रकम',
  'Target date': 'लक्ष्य मिति',
  'Goal added.': 'लक्ष्य थपियो।',
  'Goal updated.': 'लक्ष्य अद्यावधिक भयो।',
  'Delete savings goal?': 'बचत लक्ष्य मेटाउने?',
  'This savings goal will be permanently removed.': 'यो बचत लक्ष्य स्थायी रूपमा हटाइनेछ।',
  'Goal deleted.': 'लक्ष्य मेटाइयो।',
  'Search, filter, and manage your recorded activity.': 'आफ्ना रेकर्ड गरिएका गतिविधि खोज्नुहोस्, छान्नुहोस् र व्यवस्थापन गर्नुहोस्।',
  'Add transaction': 'कारोबार थप्नुहोस्',
  'Edit transaction': 'कारोबार सम्पादन गर्नुहोस्',
  'Title': 'शीर्षक',
  'Account': 'खाता',
  'Select an account': 'खाता छान्नुहोस्',
  Description: 'विवरण',
  'Delete transaction?': 'कारोबार मेटाउने?',
  'This permanently removes the transaction from your account.': 'यो कारोबार तपाईंको खाताबाट स्थायी रूपमा हटाइनेछ।',
  'Transaction added.': 'कारोबार थपियो।',
  'Transaction updated.': 'कारोबार अद्यावधिक भयो।',
  'Transaction deleted.': 'कारोबार मेटाइयो।',
  'Preferences stay in localStorage. Passwords are never saved.': 'प्राथमिकताहरू यस उपकरणमा सुरक्षित हुन्छन्। पासवर्डहरू कहिल्यै सुरक्षित गरिँदैनन्।',
  Profile: 'प्रोफाइल',
  'Profile updated.': 'प्रोफाइल अद्यावधिक भयो।',
  Appearance: 'देखावट',
  Theme: 'थिम',
  Light: 'उज्यालो',
  Dark: 'गाढा',
  System: 'प्रणाली',
  Currency: 'मुद्रा',
  'Display currency': 'देखाइने मुद्रा',
  'Email summaries': 'इमेल सारांशहरू',
  'Push alerts': 'पुस सूचनाहरू',
  'Budget alerts': 'बजेट सूचनाहरू',
  Security: 'सुरक्षा',
  'Change your password using your current credentials.': 'हालको प्रमाण प्रयोग गरेर पासवर्ड परिवर्तन गर्नुहोस्।',
  'Current password': 'हालको पासवर्ड',
  'New password': 'नयाँ पासवर्ड',
  'Update password': 'पासवर्ड अद्यावधिक गर्नुहोस्',
  'Password updated.': 'पासवर्ड अद्यावधिक भयो।',
  'All types': 'सबै प्रकार',
  'All categories': 'सबै वर्ग',
  'Search': 'खोज्नुहोस्',
  'Payment source': 'भुक्तानी स्रोत',
  'All sources': 'सबै स्रोत',
  'Sort': 'क्रमबद्ध गर्नुहोस्',
  'Newest first': 'नयाँ पहिले',
  'Oldest first': 'पुरानो पहिले',
  'Amount high to low': 'रकम ठूलोदेखि सानो',
  'Amount low to high': 'रकम सानोदेखि ठूलो',
  From: 'देखि',
  To: 'सम्म',
  'Income report': 'आम्दानी प्रतिवेदन',
  'Expense report': 'खर्च प्रतिवेदन',
  'Monthly report': 'मासिक प्रतिवेदन',
  'Yearly report': 'वार्षिक प्रतिवेदन',
  'Category report': 'वर्गगत प्रतिवेदन',
  'Full name': 'पूरा नाम',
  Email: 'इमेल',
  Password: 'पासवर्ड',
  'Create your Finora account': 'Finora खाता खोल्नुहोस्',
  'Get started': 'सुरु गर्नुहोस्',
  'Already have an account?': 'पहिले नै खाता छ?',
  'Forgot password': 'पासवर्ड बिर्सनुभयो?',
  'Password must be at least 8 characters.': 'पासवर्ड कम्तीमा ८ अक्षरको हुनुपर्छ।',
  'Password must contain at least one uppercase letter.': 'पासवर्डमा कम्तीमा एउटा ठूलो अक्षर हुनुपर्छ।',
  'Password must contain at least one lowercase letter.': 'पासवर्डमा कम्तीमा एउटा सानो अक्षर हुनुपर्छ।',
  'Password must contain at least one number.': 'पासवर्डमा कम्तीमा एउटा अंक हुनुपर्छ।',
  'Passwords do not match.': 'पासवर्डहरू मेल खाँदैनन्।',
  'Use at least 8 characters with uppercase, lowercase, and a number.': 'कम्तीमा ८ अक्षर, एउटा ठूलो अक्षर, एउटा सानो अक्षर र एउटा अंक प्रयोग गर्नुहोस्।',
  'Save profile': 'प्रोफाइल सुरक्षित गर्नुहोस्',
  'English address cannot be changed from this page.': 'यो पृष्ठबाट इमेल ठेगाना परिवर्तन गर्न सकिँदैन।',
  'Personal Information': 'व्यक्तिगत जानकारी',
  'Update the information associated with your account.': 'तपाईंको खातासँग सम्बन्धित जानकारी अद्यावधिक गर्नुहोस्।',
  'Email Address': 'इमेल ठेगाना',
  'Phone Number': 'फोन नम्बर',
  'Enter your full name': 'आफ्नो पूरा नाम लेख्नुहोस्',
  'Enter your phone number': 'आफ्नो फोन नम्बर लेख्नुहोस्',
  'Save Changes': 'परिवर्तनहरू सुरक्षित गर्नुहोस्',
  'Saving...': 'सुरक्षित हुँदैछ...',
  'Keep your Finora account secure.': 'आफ्नो Finora खाता सुरक्षित राख्नुहोस्।',
  'Change your account password regularly.': 'आफ्नो खाताको पासवर्ड नियमित रूपमा परिवर्तन गर्नुहोस्।',
  'Change Password': 'पासवर्ड परिवर्तन गर्नुहोस्',
  Edit: 'सम्पादन गर्नुहोस्',
  'No money sources yet': 'अहिलेसम्म रकमको स्रोत छैन',
  'Add a bank account, wallet, or cash source to start.': 'सुरु गर्न बैंक खाता, वालेट वा नगद स्रोत थप्नुहोस्।',
  'Nepalese Rupee': 'नेपाली रुपैयाँ',
  'US Dollar': 'अमेरिकी डलर',
  'Indian Rupee': 'भारतीय रुपैयाँ',
  Salary: 'तलब',
  Freelance: 'स्वतन्त्र काम',
  Food: 'खाना',
  Transport: 'यातायात',
  Rent: 'भाडा',
  Internet: 'इन्टरनेट',
  Shopping: 'किनमेल',
  Entertainment: 'मनोरञ्जन',
  Education: 'शिक्षा',
  Utilities: 'उपयोगिता',
  Health: 'स्वास्थ्य',
  'Create account': 'खाता खोल्नुहोस्',
  'Confirm password': 'पासवर्ड पुष्टि गर्नुहोस्',
  'Reset password': 'पासवर्ड रिसेट गर्नुहोस्',
  'Enter the email address associated with your account.': 'आफ्नो खातासँग सम्बन्धित इमेल ठेगाना लेख्नुहोस्।',
  'Send reset link': 'रिसेट लिंक पठाउनुहोस्',
  'Back to sign in': 'साइन इनमा फर्कनुहोस्',
  'Create a new password for your Finora account.': 'आफ्नो Finora खाताका लागि नयाँ पासवर्ड बनाउनुहोस्।',
  'Password reset successfully.': 'पासवर्ड सफलतापूर्वक रिसेट भयो।',
  'No email available': 'इमेल उपलब्ध छैन',
  Status: 'स्थिति',
  Active: 'सक्रिय',
  'Manage your personal information and account details.': 'आफ्नो व्यक्तिगत जानकारी र खाता विवरण व्यवस्थापन गर्नुहोस्।',
  'Profile updated successfully.': 'प्रोफाइल सफलतापूर्वक अद्यावधिक भयो।',
  'Our Story': 'हाम्रो कथा',
  'Built for Nepal.': 'नेपालका लागि बनाइएको।',
  'Designed for clarity.': 'स्पष्टताका लागि डिजाइन गरिएको।',
  'Built for Nepal. Designed for clarity.': 'नेपालका लागि बनाइएको। स्पष्टताका लागि डिजाइन गरिएको।',
  'Nepal-First': 'नेपाल-प्रथम',
  'Radical Clarity': 'पूर्ण स्पष्टता',
  'Privacy by Design': 'डिजाइनमै गोपनीयता',
  'Always Improving': 'सधैँ सुधार हुँदै',
  'Built for the Nepali financial reality — NPR-native, multi-source wallet support, and local spending patterns at the core.': 'नेपाली वित्तीय वास्तविकताका लागि बनाइएको—नेपाली रुपैयाँ, विभिन्न वालेट स्रोत र स्थानीय खर्चका ढाँचालाई केन्द्रमा राखेर।',
  'No jargon, no clutter. Every chart, card, and number is designed to tell you one thing: where your money actually is.': 'जटिल शब्द वा अनावश्यक सामग्री छैन। हरेक चार्ट, कार्ड र अंकले तपाईंको पैसा वास्तवमा कहाँ छ भन्ने कुरा स्पष्ट गर्छ।',
  'Your financial data stays yours. Zero third-party selling, JWT-secured sessions, and encrypted credentials.': 'तपाईंको वित्तीय विवरण तपाईंकै रहन्छ। तेस्रो पक्षलाई बिक्री हुँदैन, सत्र JWT बाट सुरक्षित हुन्छन् र प्रमाणहरू इन्क्रिप्ट गरिन्छन्।',
  'Finora ships iteratively. Features are added based on real user feedback, not investor decks.': 'Finora क्रमिक रूपमा सुधार हुँदै जान्छ। सुविधा लगानीकर्ताका प्रस्तुति होइन, प्रयोगकर्ताको वास्तविक प्रतिक्रियाका आधारमा थपिन्छन्।',
  'Our Mission': 'हाम्रो उद्देश्य',
  'What we stand for': 'हाम्रा मान्यता',
  'Four principles guide every decision we make at Finora.': 'Finora का हरेक निर्णयलाई चार सिद्धान्तले मार्गदर्शन गर्छन्।',
  'Built with': 'निर्माणमा प्रयोग भएका प्रविधि',
  'Boring, proven technology — because your money deserves reliability over hype.': 'तपाईंको पैसाका लागि प्रचारभन्दा भरपर्दोपन महत्त्वपूर्ण भएकाले प्रमाणित प्रविधि प्रयोग गरिएको छ।',
  'Ready to take control?': 'आफ्नो वित्त नियन्त्रण गर्न तयार हुनुहुन्छ?',
  'Join Finora for free. No credit card. No BS.': 'Finora मा निःशुल्क जोडिनुहोस्। क्रेडिट कार्ड आवश्यक छैन।',
  'Get Started Free': 'निःशुल्क सुरु गर्नुहोस्',
  'See Features': 'सुविधाहरू हेर्नुहोस्',
  'Get in touch': 'सम्पर्क गर्नुहोस्',
  'Have a question, suggestion, or feedback? Send us a message and we’ll get back to you soon.': 'प्रश्न, सुझाव वा प्रतिक्रिया छ? सन्देश पठाउनुहोस्, हामी छिट्टै जवाफ दिनेछौँ।',
  'Have a question, suggestion, or feedback? Send us a message and we\'ll get back to you soon.': 'प्रश्न, सुझाव वा प्रतिक्रिया छ? सन्देश पठाउनुहोस्, हामी छिट्टै जवाफ दिनेछौँ।',
  Message: 'सन्देश',
  'Tell us how we can help...': 'हामी कसरी मद्दत गर्न सक्छौँ भन्नुहोस्...',
  'Send message': 'सन्देश पठाउनुहोस्',
  'Message sent successfully': 'सन्देश सफलतापूर्वक पठाइयो',
  'Thank you for contacting us. We\'ll get back to you soon.': 'सम्पर्क गर्नुभएकोमा धन्यवाद। हामी छिट्टै जवाफ दिनेछौँ।',
  'Simple, transparent pricing': 'सरल र पारदर्शी मूल्य',
  Personal: 'व्यक्तिगत',
  Plus: 'प्लस',
  Free: 'निःशुल्क',
  Unavailable: 'उपलब्ध छैन',
  'Personal finance tracking': 'व्यक्तिगत वित्त ट्र्याकिङ',
  'Accounts, budgets, and goals': 'खाता, बजेट र लक्ष्यहरू',
  'Reports and analytics': 'प्रतिवेदन र विश्लेषण',
  'All Personal features': 'व्यक्तिगत योजनाका सबै सुविधा',
  'Time-limited Plus access': 'निश्चित अवधिको प्लस पहुँच',
  'eSewa-verified checkout': 'eSewa बाट प्रमाणित भुक्तानी',
  'Opening eSewa...': 'eSewa खोलिँदैछ...',
  'Subscribe with eSewa': 'eSewa मार्फत सदस्यता लिनुहोस्',
  'Sign in to subscribe': 'सदस्यता लिन साइन इन गर्नुहोस्',
  'Plus checkout is not configured yet.': 'प्लस भुक्तानी अझै सेटअप गरिएको छैन।',
  'Payment needs attention': 'भुक्तानीमा ध्यान दिनुहोस्',
  'Payment not completed': 'भुक्तानी पूरा भएन',
  'Verifying payment': 'भुक्तानी प्रमाणित हुँदैछ',
  'Plus activated': 'प्लस सक्रिय भयो',
  'Sign in to verify this payment.': 'यो भुक्तानी प्रमाणित गर्न साइन इन गर्नुहोस्।',
  'eSewa did not return a payment receipt. No subscription was activated.': 'eSewa बाट भुक्तानी रसिद आएन। सदस्यता सक्रिय गरिएको छैन।',
  'eSewa has not confirmed this payment': 'eSewa ले यो भुक्तानी पुष्टि गरेको छैन',
  'eSewa confirmed the payment and your Plus access is active.': 'eSewa ले भुक्तानी पुष्टि गरेको छ र तपाईंको प्लस पहुँच सक्रिय छ।',
  'The payment was cancelled or not completed. No Plus access was granted.': 'भुक्तानी रद्द भयो वा पूरा भएन। प्लस पहुँच दिइएको छैन।',
  'Checking the payment directly with eSewa.': 'eSewa सँग भुक्तानी जाँच हुँदैछ।',
  'Go to dashboard': 'ड्यासबोर्डमा जानुहोस्',
  'Page Not Found': 'पृष्ठ भेटिएन',
  'This page is not in Finora': 'यो पृष्ठ Finora मा छैन',
  'The route you opened does not exist. Head back to the homepage or dashboard.': 'तपाईंले खोल्नुभएको पृष्ठ छैन। गृहपृष्ठ वा ड्यासबोर्डमा फर्कनुहोस्।',
  'Sorry, we couldn\'t find the page you\'re looking for. It may have been moved, deleted, or the URL may be incorrect.': 'माफ गर्नुहोस्, तपाईंले खोज्नुभएको पृष्ठ भेटिएन। यो सारिएको, मेटिएको वा URL गलत हुन सक्छ।',
  'Good morning': 'शुभ प्रभात',
  'Good afternoon': 'शुभ दिउँसो',
  'Good evening': 'शुभ साँझ',
  'Total money': 'कुल रकम',
  'vs last month': 'गत महिनाको तुलनामा',
  'Switch to light mode': 'उज्यालो मोडमा बदल्नुहोस्',
  'Switch to dark mode': 'गाढा मोडमा बदल्नुहोस्',
  'Light mode': 'उज्यालो मोड',
  'Dark mode': 'गाढा मोड',
  'Switch language to Nepali': 'नेपाली भाषामा बदल्नुहोस्',
  'Switch language to English': 'अंग्रेजी भाषामा बदल्नुहोस्',
  'Mobile dashboard': 'मोबाइल ड्यासबोर्ड',
  'Close navigation drawer': 'नेभिगेसन बन्द गर्नुहोस्',
  'Show password': 'पासवर्ड देखाउनुहोस्',
  'Hide password': 'पासवर्ड लुकाउनुहोस्',
  'Reset your password': 'आफ्नो पासवर्ड रिसेट गर्नुहोस्',
  'Please fill in all fields.': 'कृपया सबै विवरण भर्नुहोस्।',
  'Invalid or missing password reset token.': 'पासवर्ड रिसेट टोकन अमान्य छ वा उपलब्ध छैन।',
  'This password reset link is invalid or missing a reset token.': 'यो पासवर्ड रिसेट लिंक अमान्य छ वा टोकन छैन।',
  'Request a new reset link': 'नयाँ रिसेट लिंक अनुरोध गर्नुहोस्',
  'Enter your new password': 'आफ्नो नयाँ पासवर्ड लेख्नुहोस्',
  'Confirm your new password': 'नयाँ पासवर्ड पुष्टि गर्नुहोस्',
  'Password must contain:': 'पासवर्डमा यी कुरा हुनुपर्छ:',
  'At least 8 characters': 'कम्तीमा ८ अक्षर',
  'At least one uppercase letter': 'कम्तीमा एउटा ठूलो अक्षर',
  'At least one lowercase letter': 'कम्तीमा एउटा सानो अक्षर',
  'At least one number': 'कम्तीमा एउटा अंक',
  'Resetting password...': 'पासवर्ड रिसेट हुँदैछ...',
  'Password reset delivery is not configured. Please contact support.': 'पासवर्ड रिसेट सेवा सेटअप गरिएको छैन। कृपया सहयोग टोलीलाई सम्पर्क गर्नुहोस्।',
  'Email is required.': 'इमेल आवश्यक छ।',
  'Enter a valid email address.': 'मान्य इमेल ठेगाना लेख्नुहोस्।',
  'Name is required.': 'नाम आवश्यक छ।',
  'Name must be at least 2 characters.': 'नाम कम्तीमा २ अक्षरको हुनुपर्छ।',
  'Message is required.': 'सन्देश आवश्यक छ।',
  'Full name is required.': 'पूरा नाम आवश्यक छ।',
  'Full name must be at least 2 characters.': 'पूरा नाम कम्तीमा २ अक्षरको हुनुपर्छ।',
  'Something went wrong. Please try again.': 'केही समस्या भयो। कृपया फेरि प्रयास गर्नुहोस्।',
  'for': 'का लागि',
  days: 'दिन',
  'one-time payment': 'एकपटकको भुक्तानी',
  'Finora started as a frustration. Most finance apps are built for Western banking systems — one bank account, one currency, credit cards everywhere. In Nepal, money lives in bank accounts, eSewa wallets, Khalti, and cash simultaneously. We built Finora to match that reality.': 'Finora को सुरुवात एउटा असन्तुष्टिबाट भयो। धेरै वित्तीय एपहरू पश्चिमी बैंकिङ प्रणालीका लागि बनेका छन्—एउटा बैंक खाता, एउटा मुद्रा र जताततै क्रेडिट कार्ड। नेपालमा पैसा बैंक खाता, eSewa वालेट, Khalti र नगदमा एकैसाथ हुन्छ। यही वास्तविकताअनुसार हामीले Finora बनायौँ।',
  'To give every Nepali a clear, unified view of their finances — regardless of how many wallets, banks, or cash envelopes they juggle daily.': 'हरेक नेपालीलाई आफ्नो वित्तको स्पष्ट र एकीकृत दृश्य दिनु, चाहे उनीहरूले दैनिक कति वालेट, बैंक वा नगद स्रोत चलाउँछन्।',
  'We believe financial clarity is not a luxury. It is the foundation of every good decision: whether to save for a motorbike, plan a trek, or support a family back home.': 'हामी वित्तीय स्पष्टतालाई विलासिता होइन, हरेक राम्रो निर्णयको आधार मान्छौँ—मोटरसाइकलका लागि बचत गर्ने, पदयात्रा योजना बनाउने वा परिवारलाई सहयोग गर्ने निर्णय।',
  'Finance modules': 'वित्तीय खण्डहरू',
  'Native currency': 'स्थानीय मुद्रा',
  'Accounts supported': 'समर्थित खाताहरू',
  'Data sold': 'बिक्री गरिएका डेटा',
  Frontend: 'फ्रन्टएन्ड',
  Styling: 'शैलीकरण',
  Backend: 'ब्याकएन्ड',
  Database: 'डाटाबेस',
  Auth: 'प्रमाणीकरण',
  Validation: 'प्रमाणीकरण जाँच',
  'What this could feel like': 'Finora प्रयोग गर्दा यस्तो अनुभव हुनेछ',
  'Hi! I’m Finora Guide. Ask me about your balance, spending, budgets, or savings goals.': 'नमस्कार! म Finora Guide हुँ। आफ्नो मौज्दात, खर्च, बजेट वा बचत लक्ष्यबारे सोध्नुहोस्।',
  'Your personal finance assistant': 'तपाईंको व्यक्तिगत वित्त सहायक',
  'Close chat': 'कुराकानी बन्द गर्नुहोस्',
  'Ask about your finances': 'आफ्नो वित्तबारे सोध्नुहोस्',
  there: 'त्यहाँ',
  Close: 'बन्द गर्नुहोस्',
  'Open Finora Guide': 'Finora Guide खोल्नुहोस्',
  'Close Finora Guide': 'Finora Guide बन्द गर्नुहोस्',
  'Finora Guide chat': 'Finora Guide कुराकानी',
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem(STORAGE_KEYS.language) || 'en')

  useEffect(() => {
    localStorage.setItem(STORAGE_KEYS.language, language)
    document.documentElement.lang = language === 'ne' ? 'ne' : 'en'
  }, [language])

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      toggleLanguage: () => setLanguage((current) => (current === 'en' ? 'ne' : 'en')),
      t: (text) => (language === 'ne' ? nepaliTranslations[text] || text : text),
    }),
    [language],
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}
